/**
 * Catálogo de atajos de teclado de la página Atajos.
 * `try`: se puede simular con el botón "Probar" (solo combinaciones de la tecla Windows).
 * `win11`: solo en Windows 11.
 */
export interface Shortcut {
  keys: string[];
  what: string;
  tip?: string;
  try?: boolean;
  win11?: boolean;
}

export interface ShortcutGroup {
  id: string;
  title: string;
  intro: string;
  items: Shortcut[];
}

export const SHORTCUT_GROUPS: ShortcutGroup[] = [
  {
    id: "essentials",
    title: "Imprescindibles",
    intro: "Los que se usan a diario en casi cualquier programa.",
    items: [
      { keys: ["Ctrl", "C"], what: "Copiar" },
      { keys: ["Ctrl", "X"], what: "Cortar" },
      { keys: ["Ctrl", "V"], what: "Pegar" },
      { keys: ["Ctrl", "Z"], what: "Deshacer" },
      { keys: ["Ctrl", "Y"], what: "Rehacer" },
      { keys: ["Ctrl", "A"], what: "Seleccionar todo" },
      { keys: ["Ctrl", "S"], what: "Guardar" },
      { keys: ["Ctrl", "P"], what: "Imprimir" },
      { keys: ["Ctrl", "F"], what: "Buscar dentro del documento o la página" },
      { keys: ["Ctrl", "N"], what: "Nuevo documento o ventana" },
      { keys: ["Ctrl", "W"], what: "Cerrar el documento o pestaña actual" },
      { keys: ["Alt", "Tab"], what: "Cambiar entre ventanas abiertas", tip: "Mantén Alt y pulsa Tab varias veces para elegir." },
      { keys: ["Alt", "F4"], what: "Cerrar la ventana actual", tip: "Sobre el escritorio abre el menú de apagar/reiniciar." },
      { keys: ["F2"], what: "Cambiar el nombre del archivo o carpeta seleccionado" },
      { keys: ["F5"], what: "Actualizar la ventana o la página" },
      { keys: ["Shift", "Supr"], what: "Borrar sin pasar por la papelera", tip: "No se puede recuperar desde la papelera: úsalo con cuidado." },
      { keys: ["Ctrl", "Shift", "Esc"], what: "Abrir directamente el Administrador de tareas" },
      { keys: ["Esc"], what: "Cancelar o cerrar el menú o cuadro de diálogo" },
    ],
  },
  {
    id: "windows",
    title: "Tecla Windows",
    intro: "Accesos directos a funciones de Windows. La mayoría se pueden probar con el botón.",
    items: [
      { keys: ["Win"], what: "Abrir o cerrar el menú Inicio" },
      { keys: ["Win", "D"], what: "Mostrar el escritorio (y volver)", try: true },
      { keys: ["Win", "E"], what: "Abrir el Explorador de archivos", try: true },
      { keys: ["Win", "I"], what: "Abrir Configuración", try: true },
      { keys: ["Win", "R"], what: "Abrir Ejecutar (services.msc, cmd, appwiz.cpl…)", try: true },
      { keys: ["Win", "S"], what: "Buscar en Windows", try: true },
      { keys: ["Win", "X"], what: "Menú de administración: Terminal, Dispositivos, Discos…", tip: "Después, la letra subrayada abre cada opción: Win+X y luego A abre la terminal como administrador.", try: true },
      { keys: ["Win", "L"], what: "Bloquear el equipo", tip: "Hábito clave al levantarte del ordenador de un cliente." },
      { keys: ["Win", "V"], what: "Historial del portapapeles (lo último que copiaste)", tip: "La primera vez pide activarlo. Permite fijar textos que pegas a menudo.", try: true },
      { keys: ["Win", "."], what: "Emojis, símbolos y caracteres especiales", try: true },
      { keys: ["Win", "A"], what: "Configuración rápida (Wi-Fi, Bluetooth, volumen, brillo)", try: true, win11: true },
      { keys: ["Win", "N"], what: "Notificaciones y calendario", try: true, win11: true },
      { keys: ["Win", "W"], what: "Widgets", try: true, win11: true },
      { keys: ["Win", "H"], what: "Dictado por voz (escribir hablando)", try: true },
      { keys: ["Win", "K"], what: "Conectar a una pantalla o dispositivo inalámbrico", try: true },
      { keys: ["Win", "P"], what: "Modo de proyección: duplicar, extender, solo segunda pantalla", tip: "Salva cuando un proyector o un monitor no muestra nada.", try: true },
      { keys: ["Win", "G"], what: "Barra de juego de Xbox (grabar, rendimiento)", try: true },
      { keys: ["Win", "U"], what: "Configuración de accesibilidad", try: true },
      { keys: ["Win", "Pause"], what: "Información del sistema (Configuración → Acerca de)", try: true },
      { keys: ["Win", "M"], what: "Minimizar todas las ventanas", try: true },
      { keys: ["Win", "Shift", "M"], what: "Restaurar las ventanas minimizadas", try: true },
      { keys: ["Win", "Home"], what: "Minimizar todas menos la activa", try: true },
      { keys: ["Win", "T"], what: "Recorrer los programas de la barra de tareas", try: true },
      { keys: ["Win", "B"], what: "Ir a los iconos junto al reloj (bandeja del sistema)", try: true },
      { keys: ["Win", "1…9"], what: "Abrir el programa anclado en esa posición de la barra de tareas" },
      { keys: ["Win", "Alt", "D"], what: "Mostrar la fecha y la hora", try: true },
      { keys: ["Win", "Ctrl", "Q"], what: "Asistencia rápida (ayuda remota con un código)", tip: "El atajo más útil para que un cliente te deje entrar a su equipo.", try: true },
      { keys: ["Win", "Space"], what: "Cambiar el idioma o distribución del teclado", try: true },
      { keys: ["Win", "Ctrl", "V"], what: "Elegir por dónde sale el sonido (altavoces, auriculares…)", try: true, win11: true },
      { keys: ["Win", "Alt", "K"], what: "Silenciar o activar el micrófono en una llamada (Teams y otras apps compatibles)", win11: true },
      { keys: ["Win", ","], what: "Echar un vistazo al escritorio mientras se mantiene pulsado" },
      { keys: ["Win", "O"], what: "Bloquear la orientación de la pantalla (tablets y convertibles)" },
      { keys: ["Win", "C"], what: "Copilot (o Chat de Teams, según la versión)", win11: true },
      { keys: ["Win", "F"], what: "Centro de opiniones (enviar un fallo a Microsoft)", try: true },
      { keys: ["Win", "Ctrl", "F"], what: "Buscar equipos en la red del dominio" },
      { keys: ["Win", "Alt", "Up"], what: "Ajustar la ventana a la mitad superior", win11: true },
      { keys: ["Win", "Alt", "Down"], what: "Ajustar la ventana a la mitad inferior", win11: true },
      { keys: ["Win", "Shift", "Up"], what: "Estirar la ventana de arriba abajo sin cambiar su ancho" },
    ],
  },
  {
    id: "windows-mgmt",
    title: "Ventanas y escritorios",
    intro: "Ordenar ventanas y trabajar con varios escritorios y monitores.",
    items: [
      { keys: ["Win", "Left"], what: "Ajustar la ventana a la mitad izquierda" },
      { keys: ["Win", "Right"], what: "Ajustar la ventana a la mitad derecha" },
      { keys: ["Win", "Up"], what: "Maximizar la ventana" },
      { keys: ["Win", "Down"], what: "Restaurar o minimizar la ventana" },
      { keys: ["Win", "Z"], what: "Diseños de ajuste (colocar ventanas en cuadrícula)", try: true, win11: true },
      { keys: ["Win", "Shift", "Left"], what: "Mover la ventana al monitor de la izquierda" },
      { keys: ["Win", "Shift", "Right"], what: "Mover la ventana al monitor de la derecha" },
      { keys: ["Win", "Tab"], what: "Vista de tareas: todas las ventanas y escritorios", try: true },
      { keys: ["Win", "Ctrl", "D"], what: "Crear un escritorio virtual nuevo" },
      { keys: ["Win", "Ctrl", "Left"], what: "Ir al escritorio virtual anterior" },
      { keys: ["Win", "Ctrl", "Right"], what: "Ir al escritorio virtual siguiente" },
      { keys: ["Win", "Ctrl", "F4"], what: "Cerrar el escritorio virtual actual" },
      { keys: ["Alt", "Space"], what: "Menú de la ventana (mover, tamaño, cerrar)" },
      { keys: ["Ctrl", "Alt", "Tab"], what: "Cambiar de ventana sin mantener pulsado Alt" },
      { keys: ["Alt", "Esc"], what: "Pasar a la siguiente ventana en el orden en que se abrieron" },
    ],
  },
  {
    id: "capture",
    title: "Capturas de pantalla",
    intro: "Para documentar un error o enviar lo que se ve.",
    items: [
      { keys: ["Win", "Shift", "S"], what: "Recortar una zona de la pantalla (va al portapapeles)", tip: "La notificación permite anotar y guardar la captura.", try: true },
      { keys: ["PrtScn"], what: "Capturar la pantalla completa (o abrir Recortes, según la configuración)" },
      { keys: ["Win", "PrtScn"], what: "Guardar la pantalla completa en Imágenes → Capturas de pantalla", try: true },
      { keys: ["Alt", "PrtScn"], what: "Capturar solo la ventana activa al portapapeles" },
      { keys: ["Win", "Alt", "R"], what: "Grabar vídeo de la ventana (barra de juego)" },
      { keys: ["Win", "Alt", "PrtScn"], what: "Capturar la ventana activa y guardarla (barra de juego)" },
    ],
  },
  {
    id: "explorer",
    title: "Explorador de archivos",
    intro: "Moverse por carpetas mucho más rápido.",
    items: [
      { keys: ["Ctrl", "Shift", "N"], what: "Crear una carpeta nueva" },
      { keys: ["Alt", "Enter"], what: "Propiedades del archivo o carpeta" },
      { keys: ["Alt", "Up"], what: "Subir a la carpeta superior" },
      { keys: ["Alt", "Left"], what: "Volver a la carpeta anterior" },
      { keys: ["Alt", "Right"], what: "Avanzar" },
      { keys: ["Ctrl", "L"], what: "Ir a la barra de direcciones (escribe una ruta o %temp%)", tip: "También Alt+D o F4." },
      { keys: ["Ctrl", "E"], what: "Ir al cuadro de búsqueda" },
      { keys: ["Ctrl", "T"], what: "Nueva pestaña del Explorador", win11: true },
      { keys: ["Ctrl", "Shift", "C"], what: "Copiar la ruta completa del elemento seleccionado", win11: true },
      { keys: ["Shift", "F10"], what: "Menú contextual (clic derecho) del elemento seleccionado", tip: "En Windows 11 muestra el menú completo clásico." },
      { keys: ["Alt", "P"], what: "Mostrar u ocultar el panel de vista previa" },
      { keys: ["Ctrl", "Shift", "6"], what: "Ver como detalles (columnas de tamaño, fecha…)" },
      { keys: ["Ctrl", "Rueda del ratón"], what: "Cambiar el tamaño de los iconos" },
      { keys: ["Ctrl", "W"], what: "Cerrar la ventana o pestaña del Explorador" },
      { keys: ["Ctrl", "Shift", "E"], what: "Desplegar en el panel izquierdo la carpeta actual" },
      { keys: ["Alt", "D"], what: "Ir a la barra de direcciones (igual que Ctrl+L)" },
      { keys: ["Ctrl", "Shift", "2"], what: "Ver como iconos grandes (1: extragrandes, 3: medianos, 4: pequeños)" },
      { keys: ["F11"], what: "Explorador a pantalla completa" },
      { keys: ["Alt", "Shift", "P"], what: "Mostrar u ocultar el panel de detalles" },
      { keys: ["Ctrl", "Clic"], what: "Seleccionar varios archivos sueltos" },
      { keys: ["Shift", "Clic"], what: "Seleccionar un rango de archivos seguidos" },
    ],
  },
  {
    id: "text",
    title: "Escribir y editar texto",
    intro: "Funcionan en Word, el navegador, el correo y casi cualquier cuadro de texto.",
    items: [
      { keys: ["Ctrl", "Left / Right"], what: "Saltar palabra a palabra" },
      { keys: ["Ctrl", "Shift", "Left / Right"], what: "Seleccionar palabra a palabra" },
      { keys: ["Home / End"], what: "Ir al principio o al final de la línea" },
      { keys: ["Ctrl", "Home / End"], what: "Ir al principio o al final del documento" },
      { keys: ["Shift", "Home / End"], what: "Seleccionar hasta el principio o el final de la línea" },
      { keys: ["Ctrl", "Retroceso"], what: "Borrar la palabra anterior entera" },
      { keys: ["Ctrl", "Supr"], what: "Borrar la palabra siguiente entera" },
      { keys: ["Ctrl", "Shift", "V"], what: "Pegar sin formato (en navegadores y muchos programas)" },
      { keys: ["Ctrl", "B"], what: "Negrita (en Word: Ctrl+N en español)" },
      { keys: ["Ctrl", "I"], what: "Cursiva (en Word en español: Ctrl+K)" },
      { keys: ["Ctrl", "U"], what: "Subrayado (en Word en español: Ctrl+S)" },
      { keys: ["Shift", "F3"], what: "Word: cambiar entre MAYÚSCULAS, minúsculas y Tipo Título" },
      { keys: ["Ctrl", "Enter"], what: "Word: salto de página" },
    ],
  },
  {
    id: "browser",
    title: "Navegador",
    intro: "Chrome, Edge, Brave y Firefox (salvo que se indique).",
    items: [
      { keys: ["Ctrl", "T"], what: "Nueva pestaña" },
      { keys: ["Ctrl", "Shift", "T"], what: "Reabrir la última pestaña cerrada", tip: "Se puede repetir para recuperar varias." },
      { keys: ["Ctrl", "Tab"], what: "Pestaña siguiente (Ctrl+Shift+Tab: anterior)" },
      { keys: ["Ctrl", "1…8"], what: "Ir a esa pestaña (Ctrl+9: la última)" },
      { keys: ["Ctrl", "L"], what: "Seleccionar la barra de direcciones" },
      { keys: ["Ctrl", "Shift", "N"], what: "Ventana de incógnito o InPrivate (Firefox: Ctrl+Shift+P)" },
      { keys: ["Ctrl", "H"], what: "Historial" },
      { keys: ["Ctrl", "J"], what: "Descargas" },
      { keys: ["Ctrl", "Shift", "Supr"], what: "Borrar datos de navegación (caché, cookies…)" },
      { keys: ["Ctrl", "F5"], what: "Recargar sin caché", tip: "Primer paso cuando una web se ve mal o desactualizada." },
      { keys: ["Ctrl", "D"], what: "Guardar la página en marcadores" },
      { keys: ["Ctrl", "Shift", "B"], what: "Mostrar u ocultar la barra de marcadores" },
      { keys: ["Ctrl", "+ / - / 0"], what: "Acercar, alejar y restablecer el zoom" },
      { keys: ["F11"], what: "Pantalla completa" },
      { keys: ["F12"], what: "Herramientas de desarrollo (consola, red)" },
      { keys: ["Alt", "Left"], what: "Página anterior" },
      { keys: ["Shift", "Esc"], what: "Chrome y Edge: administrador de tareas del navegador (qué pestaña consume más)", tip: "Ideal cuando el navegador va lento o la memoria está al límite." },
      { keys: ["Ctrl", "Shift", "Esc"], what: "Ver la memoria de cada pestaña (Edge: Ctrl+Shift+Esc abre también el de Windows)" },
      { keys: ["Ctrl", "U"], what: "Ver el código fuente de la página" },
      { keys: ["Ctrl", "Shift", "O"], what: "Administrador de marcadores" },
      { keys: ["Alt", "Enter"], what: "En la barra de direcciones: abrir en una pestaña nueva" },
      { keys: ["Ctrl", "Enter"], what: "En la barra de direcciones: añadir www. y .com" },
      { keys: ["Ctrl", "W"], what: "Cerrar la pestaña (Ctrl+Shift+W: la ventana entera)" },
      { keys: ["Ctrl", "Shift", "A"], what: "Buscar entre las pestañas abiertas" },
      { keys: ["Ctrl", "Shift", "R"], what: "Recargar sin caché (igual que Ctrl+F5)" },
      { keys: ["Ctrl", "P"], what: "Imprimir o guardar la página como PDF" },
    ],
  },
  {
    id: "excel",
    title: "Excel",
    intro: "Los que más tiempo ahorran con hojas de cálculo.",
    items: [
      { keys: ["F2"], what: "Editar la celda seleccionada" },
      { keys: ["Ctrl", "Flechas"], what: "Saltar al final de los datos en esa dirección" },
      { keys: ["Ctrl", "Shift", "Flechas"], what: "Seleccionar hasta el final de los datos" },
      { keys: ["Ctrl", "Space"], what: "Seleccionar la columna entera" },
      { keys: ["Shift", "Space"], what: "Seleccionar la fila entera" },
      { keys: ["Ctrl", "Shift", "L"], what: "Activar o quitar filtros" },
      { keys: ["Ctrl", "T"], what: "Convertir el rango en tabla" },
      { keys: ["Alt", "="], what: "Autosuma" },
      { keys: ["F4"], what: "Al escribir una fórmula: fijar la referencia ($A$1)" },
      { keys: ["Ctrl", "1"], what: "Formato de celdas" },
      { keys: ["Ctrl", "D"], what: "Rellenar hacia abajo (copiar la celda de arriba)" },
      { keys: ["Ctrl", "E"], what: "Relleno rápido: completa una columna siguiendo tu ejemplo" },
      { keys: ["Ctrl", "Re Pág / Av Pág"], what: "Cambiar de hoja" },
      { keys: ["Ctrl", ";"], what: "Escribir la fecha de hoy" },
      { keys: ["Ctrl", "Shift", ":"], what: "Escribir la hora actual" },
      { keys: ["Alt", "Enter"], what: "Salto de línea dentro de la misma celda" },
      { keys: ["Ctrl", "`"], what: "Ver las fórmulas en lugar de los resultados" },
      { keys: ["F9"], what: "Recalcular todas las fórmulas" },
      { keys: ["Ctrl", "Shift", "$"], what: "Formato de moneda" },
      { keys: ["Ctrl", "Shift", "%"], what: "Formato de porcentaje" },
      { keys: ["Ctrl", "K"], what: "Insertar un vínculo (en Excel en español: Ctrl+Alt+K)" },
      { keys: ["Ctrl", "-"], what: "Eliminar filas o columnas seleccionadas" },
      { keys: ["Ctrl", "+"], what: "Insertar filas o columnas" },
      { keys: ["Ctrl", "9"], what: "Ocultar la fila (Ctrl+0: la columna)" },
      { keys: ["Ctrl", "Shift", "7"], what: "Borde alrededor de la selección" },
    ],
  },
  {
    id: "tech",
    title: "Técnico y soporte",
    intro: "Trucos que resuelven problemas en un equipo en segundos.",
    items: [
      { keys: ["Win", "Ctrl", "Shift", "B"], what: "Reiniciar el driver de la tarjeta gráfica", tip: "Pantalla negra, congelada o con artefactos: la pantalla parpadea y suele volver. No cierra ningún programa.", try: true },
      { keys: ["Ctrl", "Alt", "Supr"], what: "Pantalla de seguridad: bloquear, cambiar usuario, Administrador de tareas", tip: "Funciona aunque el Explorador no responda." },
      { keys: ["Ctrl", "Shift", "Esc"], what: "Administrador de tareas directo", tip: "Si la barra de tareas desapareció: Archivo → Ejecutar nueva tarea → explorer.exe." },
      { keys: ["Alt", "Space", "M", "Flechas"], what: "Recuperar una ventana que quedó fuera de la pantalla", tip: "Alt+Espacio, luego M (Mover), una flecha y mueve el ratón: la ventana vuelve pegada al cursor. Clásico al quitar un segundo monitor." },
      { keys: ["Win", "Shift", "Left / Right"], what: "Traer una ventana de otro monitor" },
      { keys: ["Ctrl", "Shift", "Enter"], what: "En la búsqueda del menú Inicio o en Ejecutar: abrir como administrador" },
      { keys: ["Shift", "Reiniciar"], what: "Mantén Shift al pulsar Reiniciar: arranca en el menú de recuperación (modo seguro, restaurar…)" },
      { keys: ["Shift", "Clic derecho"], what: "En una carpeta: más opciones, como «Copiar como ruta de acceso» o abrir PowerShell ahí" },
      { keys: ["Win", "R", "msconfig"], what: "Configuración del sistema: arranque en modo seguro sin reiniciar al menú" },
      { keys: ["Win", "X", "A"], what: "Terminal como administrador en dos pulsaciones" },
      { keys: ["Win", "P"], what: "Proyector o monitor en negro: cambiar el modo de pantalla", try: true },
      { keys: ["Win", "V"], what: "Recuperar algo que el cliente copió antes (historial del portapapeles)", try: true },
      { keys: ["Ctrl", "Clic en Apagar"], what: "En la pantalla Ctrl+Alt+Supr: reinicio de emergencia si el equipo no responde" },
      { keys: ["Ctrl", "Alt", "Up"], what: "Pantalla girada: volver a la orientación normal (drivers Intel)", tip: "Si el cliente la giró sin querer con Ctrl+Alt+flecha. En otros equipos: Configuración → Pantalla → Orientación." },
      { keys: ["Win", "Ctrl", "C"], what: "Pantalla en blanco y negro: activar o quitar los filtros de color", tip: "Solo si el atajo está activado en Accesibilidad → Filtros de color; es la causa típica de «se me ha puesto gris la pantalla»." },
      { keys: ["Alt", "Shift"], what: "Teclado que escribe símbolos raros: cambiar la distribución (ES/EN)", tip: "Si al pulsar la Ñ sale otra cosa, se cambió de idioma. También Win+Espacio." },
      { keys: ["Fn", "Bloq Num"], what: "Portátil que escribe números en vez de letras: quitar el bloqueo numérico" },
      { keys: ["Ctrl", "Shift", "Esc", "Más detalles"], what: "Administrador de tareas: ver el proceso que bloquea un archivo (pestaña Rendimiento → Monitor de recursos)" },
      { keys: ["Win", "R", "%temp%"], what: "Abrir la carpeta de temporales del usuario" },
      { keys: ["Win", "R", "shell:startup"], what: "Carpeta de inicio del usuario (programas que arrancan con la sesión)" },
      { keys: ["Win", "R", "control"], what: "Panel de control clásico" },
      { keys: ["Win", "R", "ncpa.cpl"], what: "Conexiones de red (adaptadores)" },
      { keys: ["Win", "R", "appwiz.cpl"], what: "Programas y características (desinstalar a la antigua)" },
      { keys: ["Win", "R", "devmgmt.msc"], what: "Administrador de dispositivos" },
      { keys: ["Win", "R", "eventvwr"], what: "Visor de eventos" },
    ],
  },
  {
    id: "terminal",
    title: "CMD, PowerShell y Terminal",
    intro: "Trabajar en la consola sin volver a escribir los comandos.",
    items: [
      { keys: ["Tab"], what: "Completar el nombre de la carpeta, archivo o comando" },
      { keys: ["Up / Down"], what: "Recuperar los comandos anteriores" },
      { keys: ["F7"], what: "CMD: lista de los comandos usados" },
      { keys: ["Ctrl", "C"], what: "Detener el comando en curso (o copiar si hay texto seleccionado)" },
      { keys: ["Clic derecho"], what: "Pegar en CMD" },
      { keys: ["Ctrl", "Shift", "T"], what: "Terminal: nueva pestaña" },
      { keys: ["Ctrl", "Shift", "W"], what: "Terminal: cerrar la pestaña" },
      { keys: ["Alt", "Shift", "+ / -"], what: "Terminal: dividir el panel en vertical u horizontal" },
      { keys: ["Ctrl", "Shift", "P"], what: "Terminal: paleta de comandos" },
      { keys: ["Ctrl", "Shift", "F"], what: "Terminal: buscar en la salida" },
    ],
  },
  {
    id: "access",
    title: "Accesibilidad",
    intro: "Para clientes con dificultades de visión o de uso del teclado, y para saber desactivarlo si se activa sin querer.",
    items: [
      { keys: ["Win", "+"], what: "Lupa: ampliar la pantalla (Win+Esc para salir)", try: true },
      { keys: ["Win", "Ctrl", "Enter"], what: "Narrador (lee la pantalla en voz alta)", try: true },
      { keys: ["Win", "Ctrl", "O"], what: "Teclado en pantalla", try: true },
      { keys: ["Alt izq.", "Shift izq.", "PrtScn"], what: "Activar o quitar el contraste alto" },
      { keys: ["Shift ×5"], what: "Teclas especiales (si se activan sin querer, las teclas «se quedan pegadas»)" },
      { keys: ["Shift der. 8 s"], what: "Teclas filtro (el teclado «no responde» si se activan sin querer)" },
      { keys: ["Bloq Num 5 s"], what: "Teclas de alternancia (pitido al pulsar Bloq Mayús)" },
      { keys: ["Win", "Esc"], what: "Salir de la lupa" },
      { keys: ["Win", "Ctrl", "N"], what: "Configuración del Narrador" },
      { keys: ["Ctrl", "Win", "S"], what: "Reconocimiento de voz de Windows" },
      { keys: ["Ctrl", "Rueda del ratón"], what: "Ampliar texto en navegadores, Office y el Explorador" },
    ],
  },
  {
    id: "fixes",
    title: "Problemas típicos y su atajo",
    intro: "Cuando el cliente dice «no sé qué he tocado»: casi siempre es uno de estos.",
    items: [
      { keys: ["Win", "Space"], what: "La Ñ o los acentos salen mal: se cambió el idioma del teclado", tip: "Pulsa hasta que vuelva ESP. Si pasa a menudo, quita el idioma que sobra en Configuración → Hora e idioma." },
      { keys: ["Ctrl", "Alt", "Up"], what: "La pantalla está girada o al revés (drivers Intel)" },
      { keys: ["Win", "Ctrl", "C"], what: "La pantalla se ve en blanco y negro (filtros de color)" },
      { keys: ["Win", "P"], what: "No se ve nada en el proyector o el segundo monitor" },
      { keys: ["Win", "Ctrl", "Shift", "B"], what: "La pantalla se quedó negra o congelada: reiniciar el driver de vídeo" },
      { keys: ["Shift ×5"], what: "Las teclas «se quedan pegadas»: teclas especiales activadas" },
      { keys: ["Shift der. 8 s"], what: "El teclado no responde o va con retraso: teclas filtro activadas" },
      { keys: ["Bloq Num"], what: "El teclado numérico no escribe números" },
      { keys: ["Insert"], what: "Al escribir se borran las letras de delante: modo sobrescribir activado" },
      { keys: ["Win", "M"], what: "Todas las ventanas desaparecieron: se minimizaron (Win+Shift+M las devuelve)" },
      { keys: ["Alt", "Space", "M"], what: "Una ventana está fuera de la pantalla" },
      { keys: ["Ctrl", "Rueda del ratón"], what: "Todo se ve enorme o diminuto en el navegador (Ctrl+0 lo restablece)" },
      { keys: ["Fn", "F1…F12"], what: "Las teclas F cambian el brillo o el volumen en vez de funcionar: bloqueo Fn (a veces Fn+Esc)" },
      { keys: ["Ctrl", "Shift"], what: "El cursor escribe de derecha a izquierda o cambia la distribución del teclado" },
    ],
  },
  {
    id: "rdp",
    title: "Escritorio remoto",
    intro: "Dentro de una sesión de Escritorio remoto algunas combinaciones cambian, porque las recoge tu propio equipo.",
    items: [
      { keys: ["Ctrl", "Alt", "Fin"], what: "Ctrl+Alt+Supr en el equipo remoto (cambiar contraseña, Administrador de tareas)", tip: "En AnyDesk y otras herramientas suele haber un botón para enviarlo." },
      { keys: ["Ctrl", "Alt", "Pausa"], what: "Pasar de pantalla completa a ventana y al revés" },
      { keys: ["Alt", "Re Pág / Av Pág"], what: "Cambiar entre programas del equipo remoto (Alt+Tab remoto)" },
      { keys: ["Alt", "Inicio"], what: "Menú Inicio del equipo remoto" },
      { keys: ["Ctrl", "Alt", "+"], what: "Captura de todo el escritorio remoto al portapapeles" },
      { keys: ["Ctrl", "Alt", "-"], what: "Captura de la ventana activa del equipo remoto" },
      { keys: ["Ctrl", "Alt", "Inicio"], what: "Activar la barra de conexión (para salir de pantalla completa)" },
      { keys: ["Win", "Ctrl", "Q"], what: "Asistencia rápida: el cliente te da acceso con un código" },
    ],
  },
  {
    id: "word",
    title: "Word",
    intro: "Word en español usa algunas letras distintas (N de negrita, K de cursiva).",
    items: [
      { keys: ["Ctrl", "N"], what: "Negrita" },
      { keys: ["Ctrl", "K"], what: "Cursiva" },
      { keys: ["Ctrl", "S"], what: "Subrayado" },
      { keys: ["Ctrl", "G"], what: "Guardar" },
      { keys: ["Ctrl", "B"], what: "Buscar" },
      { keys: ["Ctrl", "L"], what: "Reemplazar" },
      { keys: ["Ctrl", "T"], what: "Centrar el párrafo (Ctrl+Q: alinear a la izquierda, Ctrl+D: a la derecha)" },
      { keys: ["Ctrl", "J"], what: "Justificar el párrafo" },
      { keys: ["Ctrl", "Espacio"], what: "Quitar el formato de los caracteres seleccionados" },
      { keys: ["Ctrl", "Shift", "C / V"], what: "Copiar y pegar solo el formato" },
      { keys: ["F7"], what: "Revisar ortografía y gramática" },
      { keys: ["Shift", "Enter"], what: "Salto de línea sin empezar párrafo nuevo" },
      { keys: ["Ctrl", "Z"], what: "Deshacer (también deshace la autocorrección que acaba de hacer)" },
      { keys: ["Alt", "Shift", "Up / Down"], what: "Subir o bajar el párrafo o la fila de la tabla" },
    ],
  },
  {
    id: "outlook",
    title: "Outlook",
    intro: "Correo, calendario y contactos (Outlook clásico y el nuevo).",
    items: [
      { keys: ["Ctrl", "Shift", "M"], what: "Correo nuevo desde cualquier parte de Outlook" },
      { keys: ["Ctrl", "R"], what: "Responder" },
      { keys: ["Ctrl", "Shift", "R"], what: "Responder a todos" },
      { keys: ["Ctrl", "F"], what: "Reenviar (en Outlook clásico)" },
      { keys: ["Ctrl", "Enter"], what: "Enviar el correo" },
      { keys: ["Ctrl", "Q"], what: "Marcar como leído (Ctrl+U: como no leído)" },
      { keys: ["Ctrl", "1 / 2 / 3"], what: "Ir a Correo, Calendario o Contactos" },
      { keys: ["Ctrl", "E"], what: "Buscar en el correo" },
      { keys: ["F9"], what: "Enviar y recibir ahora (Outlook clásico)" },
      { keys: ["Ctrl", "Shift", "A"], what: "Cita nueva en el calendario" },
      { keys: ["Supr"], what: "Eliminar el correo seleccionado (Shift+Supr: sin papelera)" },
    ],
  },
  {
    id: "powerpoint",
    title: "PowerPoint",
    intro: "Presentar sin buscar botones.",
    items: [
      { keys: ["F5"], what: "Presentar desde el principio" },
      { keys: ["Shift", "F5"], what: "Presentar desde la diapositiva actual" },
      { keys: ["B"], what: "Durante la presentación: pantalla en negro (W: en blanco)" },
      { keys: ["Número", "Enter"], what: "Durante la presentación: ir a esa diapositiva" },
      { keys: ["Ctrl", "L"], what: "Durante la presentación: puntero láser" },
      { keys: ["Ctrl", "M"], what: "Diapositiva nueva" },
      { keys: ["Ctrl", "D"], what: "Duplicar el objeto o la diapositiva" },
      { keys: ["Alt", "F5"], what: "Vista del moderador (notas y siguiente diapositiva)" },
    ],
  },
  {
    id: "meetings",
    title: "Reuniones: Teams, Zoom y Meet",
    intro: "Micrófono y cámara sin buscar el botón, que es lo primero que falla en una llamada.",
    items: [
      { keys: ["Ctrl", "Shift", "M"], what: "Teams: silenciar o activar el micrófono" },
      { keys: ["Ctrl", "Shift", "O"], what: "Teams: encender o apagar la cámara" },
      { keys: ["Ctrl", "Shift", "E"], what: "Teams: compartir pantalla" },
      { keys: ["Ctrl", "Shift", "K"], what: "Teams: levantar o bajar la mano" },
      { keys: ["Ctrl", "Shift", "H"], what: "Teams: colgar" },
      { keys: ["Alt", "A"], what: "Zoom: silenciar o activar el micrófono" },
      { keys: ["Alt", "V"], what: "Zoom: encender o apagar la cámara" },
      { keys: ["Alt", "S"], what: "Zoom: compartir pantalla" },
      { keys: ["Espacio (mantener)"], what: "Zoom: hablar mientras se mantiene pulsado estando silenciado" },
      { keys: ["Ctrl", "D"], what: "Google Meet: silenciar o activar el micrófono" },
      { keys: ["Ctrl", "E"], what: "Google Meet: encender o apagar la cámara" },
      { keys: ["Win", "Alt", "K"], what: "Windows 11: silenciar el micrófono en la llamada activa", win11: true },
    ],
  },
  {
    id: "adminops",
    title: "AdminOps",
    intro: "Los atajos de esta app.",
    items: [
      { keys: ["Ctrl", "K"], what: "Buscar cualquier página, herramienta, ajuste o reparación" },
      { keys: ["Ctrl", ","], what: "Ajustes" },
      { keys: ["Alt", "Left / Right"], what: "Página anterior o siguiente" },
      { keys: ["Esc"], what: "Cerrar la búsqueda o un diálogo" },
      { keys: ["Ctrl", "L"], what: "Bloquear AdminOps (si tiene PIN o contraseña)" },
      { keys: ["F5"], what: "Recargar la página actual desde cero" },
      { keys: ["Atajos propios"], what: "En Ajustes → Navegación puedes asignar una combinación a cualquier página" },
    ],
  },
];
