/**
 * Catálogo de atajos de teclado de la página Atajos.
 * `try`: se puede simular con el botón "Probar" (solo combinaciones de la tecla Windows).
 * `win11`: solo en Windows 11.
 */
export interface Shortcut {
  keys: string[];
  what: string;
  tip?: string;
  try?: boolean;
  win11?: boolean;
}

export interface ShortcutGroup {
  id: string;
  title: string;
  intro: string;
  items: Shortcut[];
}

export const SHORTCUT_GROUPS: ShortcutGroup[] = [
  {
    id: "essentials",
    title: "Imprescindibles",
    intro: "Los que se usan a diario en casi cualquier programa.",
    items: [
      { keys: ["Ctrl", "C"], what: "Copiar" },
      { keys: ["Ctrl", "X"], what: "Cortar" },
      { keys: ["Ctrl", "V"], what: "Pegar" },
      { keys: ["Ctrl", "Z"], what: "Deshacer" },
      { keys: ["Ctrl", "Y"], what: "Rehacer" },
      { keys: ["Ctrl", "A"], what: "Seleccionar todo" },
      { keys: ["Ctrl", "S"], what: "Guardar" },
      { keys: ["Ctrl", "P"], what: "Imprimir" },
      { keys: ["Ctrl", "F"], what: "Buscar dentro del documento o la página" },
      { keys: ["Ctrl", "N"], what: "Nuevo documento o ventana" },
      { keys: ["Ctrl", "W"], what: "Cerrar el documento o pestaña actual" },
      { keys: ["Alt", "Tab"], what: "Cambiar entre ventanas abiertas", tip: "Mantén Alt y pulsa Tab varias veces para elegir." },
      { keys: ["Alt", "F4"], what: "Cerrar la ventana actual", tip: "Sobre el escritorio abre el menú de apagar/reiniciar." },
      { keys: ["F2"], what: "Cambiar el nombre del archivo o carpeta seleccionado" },
      { keys: ["F5"], what: "Actualizar la ventana o la página" },
      { keys: ["Shift", "Supr"], what: "Borrar sin pasar por la papelera", tip: "No se puede recuperar desde la papelera: úsalo con cuidado." },
      { keys: ["Ctrl", "Shift", "Esc"], what: "Abrir directamente el Administrador de tareas" },
      { keys: ["Esc"], what: "Cancelar o cerrar el menú o cuadro de diálogo" },
    ],
  },
  {
    id: "windows",
    title: "Tecla Windows",
    intro: "Accesos directos a funciones de Windows. La mayoría se pueden probar con el botón.",
    items: [
      { keys: ["Win"], what: "Abrir o cerrar el menú Inicio" },
      { keys: ["Win", "D"], what: "Mostrar el escritorio (y volver)", try: true },
      { keys: ["Win", "E"], what: "Abrir el Explorador de archivos", try: true },
      { keys: ["Win", "I"], what: "Abrir Configuración", try: true },
      { keys: ["Win", "R"], what: "Abrir Ejecutar (services.msc, cmd, appwiz.cpl…)", try: true },
      { keys: ["Win", "S"], what: "Buscar en Windows", try: true },
      { keys: ["Win", "X"], what: "Menú de administración: Terminal, Dispositivos, Discos…", tip: "Después, la letra subrayada abre cada opción: Win+X y luego A abre la terminal como administrador.", try: true },
      { keys: ["Win", "L"], what: "Bloquear el equipo", tip: "Hábito clave al levantarte del ordenador de un cliente." },
      { keys: ["Win", "V"], what: "Historial del portapapeles (lo último que copiaste)", tip: "La primera vez pide activarlo. Permite fijar textos que pegas a menudo.", try: true },
      { keys: ["Win", "."], what: "Emojis, símbolos y caracteres especiales", try: true },
      { keys: ["Win", "A"], what: "Configuración rápida (Wi-Fi, Bluetooth, volumen, brillo)", try: true, win11: true },
      { keys: ["Win", "N"], what: "Notificaciones y calendario", try: true, win11: true },
      { keys: ["Win", "W"], what: "Widgets", try: true, win11: true },
      { keys: ["Win", "H"], what: "Dictado por voz (escribir hablando)", try: true },
      { keys: ["Win", "K"], what: "Conectar a una pantalla o dispositivo inalámbrico", try: true },
      { keys: ["Win", "P"], what: "Modo de proyección: duplicar, extender, solo segunda pantalla", tip: "Salva cuando un proyector o un monitor no muestra nada.", try: true },
      { keys: ["Win", "G"], what: "Barra de juego de Xbox (grabar, rendimiento)", try: true },
      { keys: ["Win", "U"], what: "Configuración de accesibilidad", try: true },
      { keys: ["Win", "Pause"], what: "Información del sistema (Configuración → Acerca de)", try: true },
      { keys: ["Win", "M"], what: "Minimizar todas las ventanas", try: true },
      { keys: ["Win", "Shift", "M"], what: "Restaurar las ventanas minimizadas", try: true },
      { keys: ["Win", "Home"], what: "Minimizar todas menos la activa", try: true },
      { keys: ["Win", "T"], what: "Recorrer los programas de la barra de tareas", try: true },
      { keys: ["Win", "B"], what: "Ir a los iconos junto al reloj (bandeja del sistema)", try: true },
      { keys: ["Win", "1…9"], what: "Abrir el programa anclado en esa posición de la barra de tareas" },
      { keys: ["Win", "Alt", "D"], what: "Mostrar la fecha y la hora", try: true },
    ],
  },
  {
    id: "windows-mgmt",
    title: "Ventanas y escritorios",
    intro: "Ordenar ventanas y trabajar con varios escritorios y monitores.",
    items: [
      { keys: ["Win", "Left"], what: "Ajustar la ventana a la mitad izquierda" },
      { keys: ["Win", "Right"], what: "Ajustar la ventana a la mitad derecha" },
      { keys: ["Win", "Up"], what: "Maximizar la ventana" },
      { keys: ["Win", "Down"], what: "Restaurar o minimizar la ventana" },
      { keys: ["Win", "Z"], what: "Diseños de ajuste (colocar ventanas en cuadrícula)", try: true, win11: true },
      { keys: ["Win", "Shift", "Left"], what: "Mover la ventana al monitor de la izquierda" },
      { keys: ["Win", "Shift", "Right"], what: "Mover la ventana al monitor de la derecha" },
      { keys: ["Win", "Tab"], what: "Vista de tareas: todas las ventanas y escritorios", try: true },
      { keys: ["Win", "Ctrl", "D"], what: "Crear un escritorio virtual nuevo" },
      { keys: ["Win", "Ctrl", "Left"], what: "Ir al escritorio virtual anterior" },
      { keys: ["Win", "Ctrl", "Right"], what: "Ir al escritorio virtual siguiente" },
      { keys: ["Win", "Ctrl", "F4"], what: "Cerrar el escritorio virtual actual" },
      { keys: ["Alt", "Space"], what: "Menú de la ventana (mover, tamaño, cerrar)" },
      { keys: ["Ctrl", "Alt", "Tab"], what: "Cambiar de ventana sin mantener pulsado Alt" },
      { keys: ["Alt", "Esc"], what: "Pasar a la siguiente ventana en el orden en que se abrieron" },
    ],
  },
  {
    id: "capture",
    title: "Capturas de pantalla",
    intro: "Para documentar un error o enviar lo que se ve.",
    items: [
      { keys: ["Win", "Shift", "S"], what: "Recortar una zona de la pantalla (va al portapapeles)", tip: "La notificación permite anotar y guardar la captura.", try: true },
      { keys: ["PrtScn"], what: "Capturar la pantalla completa (o abrir Recortes, según la configuración)" },
      { keys: ["Win", "PrtScn"], what: "Guardar la pantalla completa en Imágenes → Capturas de pantalla", try: true },
      { keys: ["Alt", "PrtScn"], what: "Capturar solo la ventana activa al portapapeles" },
      { keys: ["Win", "Alt", "R"], what: "Grabar vídeo de la ventana (barra de juego)" },
      { keys: ["Win", "Alt", "PrtScn"], what: "Capturar la ventana activa y guardarla (barra de juego)" },
    ],
  },
  {
    id: "explorer",
    title: "Explorador de archivos",
    intro: "Moverse por carpetas mucho más rápido.",
    items: [
      { keys: ["Ctrl", "Shift", "N"], what: "Crear una carpeta nueva" },
      { keys: ["Alt", "Enter"], what: "Propiedades del archivo o carpeta" },
      { keys: ["Alt", "Up"], what: "Subir a la carpeta superior" },
      { keys: ["Alt", "Left"], what: "Volver a la carpeta anterior" },
      { keys: ["Alt", "Right"], what: "Avanzar" },
      { keys: ["Ctrl", "L"], what: "Ir a la barra de direcciones (escribe una ruta o %temp%)", tip: "También Alt+D o F4." },
      { keys: ["Ctrl", "E"], what: "Ir al cuadro de búsqueda" },
      { keys: ["Ctrl", "T"], what: "Nueva pestaña del Explorador", win11: true },
      { keys: ["Ctrl", "Shift", "C"], what: "Copiar la ruta completa del elemento seleccionado", win11: true },
      { keys: ["Shift", "F10"], what: "Menú contextual (clic derecho) del elemento seleccionado", tip: "En Windows 11 muestra el menú completo clásico." },
      { keys: ["Alt", "P"], what: "Mostrar u ocultar el panel de vista previa" },
      { keys: ["Ctrl", "Shift", "6"], what: "Ver como detalles (columnas de tamaño, fecha…)" },
      { keys: ["Ctrl", "Rueda del ratón"], what: "Cambiar el tamaño de los iconos" },
    ],
  },
  {
    id: "text",
    title: "Escribir y editar texto",
    intro: "Funcionan en Word, el navegador, el correo y casi cualquier cuadro de texto.",
    items: [
      { keys: ["Ctrl", "Left / Right"], what: "Saltar palabra a palabra" },
      { keys: ["Ctrl", "Shift", "Left / Right"], what: "Seleccionar palabra a palabra" },
      { keys: ["Home / End"], what: "Ir al principio o al final de la línea" },
      { keys: ["Ctrl", "Home / End"], what: "Ir al principio o al final del documento" },
      { keys: ["Shift", "Home / End"], what: "Seleccionar hasta el principio o el final de la línea" },
      { keys: ["Ctrl", "Retroceso"], what: "Borrar la palabra anterior entera" },
      { keys: ["Ctrl", "Supr"], what: "Borrar la palabra siguiente entera" },
      { keys: ["Ctrl", "Shift", "V"], what: "Pegar sin formato (en navegadores y muchos programas)" },
      { keys: ["Ctrl", "B"], what: "Negrita (en Word: Ctrl+N en español)" },
      { keys: ["Ctrl", "I"], what: "Cursiva (en Word en español: Ctrl+K)" },
      { keys: ["Ctrl", "U"], what: "Subrayado (en Word en español: Ctrl+S)" },
      { keys: ["Shift", "F3"], what: "Word: cambiar entre MAYÚSCULAS, minúsculas y Tipo Título" },
      { keys: ["Ctrl", "Enter"], what: "Word: salto de página" },
    ],
  },
  {
    id: "browser",
    title: "Navegador",
    intro: "Chrome, Edge, Brave y Firefox (salvo que se indique).",
    items: [
      { keys: ["Ctrl", "T"], what: "Nueva pestaña" },
      { keys: ["Ctrl", "Shift", "T"], what: "Reabrir la última pestaña cerrada", tip: "Se puede repetir para recuperar varias." },
      { keys: ["Ctrl", "Tab"], what: "Pestaña siguiente (Ctrl+Shift+Tab: anterior)" },
      { keys: ["Ctrl", "1…8"], what: "Ir a esa pestaña (Ctrl+9: la última)" },
      { keys: ["Ctrl", "L"], what: "Seleccionar la barra de direcciones" },
      { keys: ["Ctrl", "Shift", "N"], what: "Ventana de incógnito o InPrivate (Firefox: Ctrl+Shift+P)" },
      { keys: ["Ctrl", "H"], what: "Historial" },
      { keys: ["Ctrl", "J"], what: "Descargas" },
      { keys: ["Ctrl", "Shift", "Supr"], what: "Borrar datos de navegación (caché, cookies…)" },
      { keys: ["Ctrl", "F5"], what: "Recargar sin caché", tip: "Primer paso cuando una web se ve mal o desactualizada." },
      { keys: ["Ctrl", "D"], what: "Guardar la página en marcadores" },
      { keys: ["Ctrl", "Shift", "B"], what: "Mostrar u ocultar la barra de marcadores" },
      { keys: ["Ctrl", "+ / - / 0"], what: "Acercar, alejar y restablecer el zoom" },
      { keys: ["F11"], what: "Pantalla completa" },
      { keys: ["F12"], what: "Herramientas de desarrollo (consola, red)" },
      { keys: ["Alt", "Left"], what: "Página anterior" },
    ],
  },
  {
    id: "excel",
    title: "Excel",
    intro: "Los que más tiempo ahorran con hojas de cálculo.",
    items: [
      { keys: ["F2"], what: "Editar la celda seleccionada" },
      { keys: ["Ctrl", "Flechas"], what: "Saltar al final de los datos en esa dirección" },
      { keys: ["Ctrl", "Shift", "Flechas"], what: "Seleccionar hasta el final de los datos" },
      { keys: ["Ctrl", "Space"], what: "Seleccionar la columna entera" },
      { keys: ["Shift", "Space"], what: "Seleccionar la fila entera" },
      { keys: ["Ctrl", "Shift", "L"], what: "Activar o quitar filtros" },
      { keys: ["Ctrl", "T"], what: "Convertir el rango en tabla" },
      { keys: ["Alt", "="], what: "Autosuma" },
      { keys: ["F4"], what: "Al escribir una fórmula: fijar la referencia ($A$1)" },
      { keys: ["Ctrl", "1"], what: "Formato de celdas" },
      { keys: ["Ctrl", "D"], what: "Rellenar hacia abajo (copiar la celda de arriba)" },
      { keys: ["Ctrl", "E"], what: "Relleno rápido: completa una columna siguiendo tu ejemplo" },
      { keys: ["Ctrl", "Re Pág / Av Pág"], what: "Cambiar de hoja" },
    ],
  },
  {
    id: "tech",
    title: "Técnico y soporte",
    intro: "Trucos que resuelven problemas en un equipo en segundos.",
    items: [
      { keys: ["Win", "Ctrl", "Shift", "B"], what: "Reiniciar el driver de la tarjeta gráfica", tip: "Pantalla negra, congelada o con artefactos: la pantalla parpadea y suele volver. No cierra ningún programa.", try: true },
      { keys: ["Ctrl", "Alt", "Supr"], what: "Pantalla de seguridad: bloquear, cambiar usuario, Administrador de tareas", tip: "Funciona aunque el Explorador no responda." },
      { keys: ["Ctrl", "Shift", "Esc"], what: "Administrador de tareas directo", tip: "Si la barra de tareas desapareció: Archivo → Ejecutar nueva tarea → explorer.exe." },
      { keys: ["Alt", "Space", "M", "Flechas"], what: "Recuperar una ventana que quedó fuera de la pantalla", tip: "Alt+Espacio, luego M (Mover), una flecha y mueve el ratón: la ventana vuelve pegada al cursor. Clásico al quitar un segundo monitor." },
      { keys: ["Win", "Shift", "Left / Right"], what: "Traer una ventana de otro monitor" },
      { keys: ["Ctrl", "Shift", "Enter"], what: "En la búsqueda del menú Inicio o en Ejecutar: abrir como administrador" },
      { keys: ["Shift", "Reiniciar"], what: "Mantén Shift al pulsar Reiniciar: arranca en el menú de recuperación (modo seguro, restaurar…)" },
      { keys: ["Shift", "Clic derecho"], what: "En una carpeta: más opciones, como «Copiar como ruta de acceso» o abrir PowerShell ahí" },
      { keys: ["Win", "R", "msconfig"], what: "Configuración del sistema: arranque en modo seguro sin reiniciar al menú" },
      { keys: ["Win", "X", "A"], what: "Terminal como administrador en dos pulsaciones" },
      { keys: ["Win", "P"], what: "Proyector o monitor en negro: cambiar el modo de pantalla", try: true },
      { keys: ["Win", "V"], what: "Recuperar algo que el cliente copió antes (historial del portapapeles)", try: true },
      { keys: ["Ctrl", "Clic en Apagar"], what: "En la pantalla Ctrl+Alt+Supr: reinicio de emergencia si el equipo no responde" },
    ],
  },
  {
    id: "terminal",
    title: "CMD, PowerShell y Terminal",
    intro: "Trabajar en la consola sin volver a escribir los comandos.",
    items: [
      { keys: ["Tab"], what: "Completar el nombre de la carpeta, archivo o comando" },
      { keys: ["Up / Down"], what: "Recuperar los comandos anteriores" },
      { keys: ["F7"], what: "CMD: lista de los comandos usados" },
      { keys: ["Ctrl", "C"], what: "Detener el comando en curso (o copiar si hay texto seleccionado)" },
      { keys: ["Clic derecho"], what: "Pegar en CMD" },
      { keys: ["Ctrl", "Shift", "T"], what: "Terminal: nueva pestaña" },
      { keys: ["Ctrl", "Shift", "W"], what: "Terminal: cerrar la pestaña" },
      { keys: ["Alt", "Shift", "+ / -"], what: "Terminal: dividir el panel en vertical u horizontal" },
      { keys: ["Ctrl", "Shift", "P"], what: "Terminal: paleta de comandos" },
      { keys: ["Ctrl", "Shift", "F"], what: "Terminal: buscar en la salida" },
    ],
  },
  {
    id: "access",
    title: "Accesibilidad",
    intro: "Para clientes con dificultades de visión o de uso del teclado, y para saber desactivarlo si se activa sin querer.",
    items: [
      { keys: ["Win", "+"], what: "Lupa: ampliar la pantalla (Win+Esc para salir)", try: true },
      { keys: ["Win", "Ctrl", "Enter"], what: "Narrador (lee la pantalla en voz alta)", try: true },
      { keys: ["Win", "Ctrl", "O"], what: "Teclado en pantalla", try: true },
      { keys: ["Alt izq.", "Shift izq.", "PrtScn"], what: "Activar o quitar el contraste alto" },
      { keys: ["Shift ×5"], what: "Teclas especiales (si se activan sin querer, las teclas «se quedan pegadas»)" },
      { keys: ["Shift der. 8 s"], what: "Teclas filtro (el teclado «no responde» si se activan sin querer)" },
      { keys: ["Bloq Num 5 s"], what: "Teclas de alternancia (pitido al pulsar Bloq Mayús)" },
    ],
  },
  {
    id: "adminops",
    title: "AdminOps",
    intro: "Los atajos de esta app.",
    items: [
      { keys: ["Ctrl", "K"], what: "Buscar cualquier página, herramienta, ajuste o reparación" },
      { keys: ["Ctrl", ","], what: "Ajustes" },
      { keys: ["Alt", "Left / Right"], what: "Página anterior o siguiente" },
      { keys: ["Esc"], what: "Cerrar la búsqueda o un diálogo" },
    ],
  },
];
