// Respuestas de ejemplo para las órdenes que, vacías, no dejarían pintar una
// pantalla (las que devuelven un objeto). Las listas vacías, cadenas y números
// los pone el simulador solo.
export const FIXTURES: Record<string, unknown> = {
  app_info: { version: "1.2.8", portable: true, dataDir: "D:\\AdminOps\\datos", reportsDir: "D:\\AdminOps\\informes", startPage: null },
  is_admin: true,
  lock_status: { enabled: false, kind: "", idleMinutes: 0, waitSecs: 0 },
  get_settings: {
    technician: "Técnico de prueba",
    company: "Soporte de ejemplo",
    phone: "",
    email: "",
    website: "",
    logo: null,
    conditions: "",
    checklist: [],
    onboarded: true,
    defaultDomain: "",
    notifyTasks: true,
    restorePoints: "risky",
    autoCleanupMonths: 0,
    checkUpdates: false,
    watchWindows: false,
    notifyAlerts: "all",
    closeMinimizes: false,
    trayIcon: false,
    visitTypes: [],
    currency: "EUR",
    taxName: "IVA",
    taxRate: 21,
    laborWarrantyDays: 90,
    maintenanceMonths: 6,
    quoteValidityDays: 30,
    catalog: [],
    techSignature: null,
    reportLayout: { name: "", technical: false, sections: [] },
  },
  get_system_info: { hostName: "PC-PRUEBAS", osName: "Windows 11 Pro", osVersion: "23H2", kernelVersion: "22631", cpuBrand: "Intel Core i5-10500", physicalCores: 6, logicalCores: 12, totalMemory: 16 * 2 ** 30, bootTime: Math.floor(Date.now() / 1000) - 3 * 3600 },
  get_live_metrics: () => ({
    cpuTotal: 10 + Math.random() * 30,
    cpuPerCore: Array.from({ length: 12 }, () => Math.random() * 60),
    memoryUsed: 7.4 * 2 ** 30,
    memoryTotal: 16 * 2 ** 30,
    swapUsed: 0,
    swapTotal: 2 ** 31,
    uptime: 3 * 3600,
    processCount: 214,
    netRxPerSec: 120_000,
    netTxPerSec: 30_000,
    disks: [{ mount: "C:\\", name: "Windows", fileSystem: "NTFS", kind: "SSD", total: 512 * 2 ** 30, available: 180 * 2 ** 30, removable: false }],
    topProcesses: [],
  }),
  recover_status: { installed: false, drives: [] },
  dns_filter_status: { active: "none", adapters: ["Ethernet"] },
  update_pause_state: { pausedUntil: null },
  network_drives: { drives: [], free: ["Z:", "Y:", "X:"] },
  troubleshoot_check: (a: { symptom: string }) => ({ symptom: a?.symptom ?? "", findings: [{ level: "warn", title: "SMBv1 está activado", detail: "Versión antigua.\nSegunda línea con 0x80070005.", fixes: [{ id: "sec.smb1", label: "Desactivar SMBv1", admin: true, confirm: null }], page: null }] }),
  crash_report: {
    groups: [{ driver: "nvlddmkm.sys", hint: "Driver de la gráfica NVIDIA.", count: 5, codes: ["0x00000116"], first: 1_727_000_000, last: 1_728_000_000, device: "NVIDIA GeForce GTX 1650", version: "31.0.15.6603", driverDate: "2024-10-03", installed: 1_726_900_000, sinceInstall: true, inf: "oem12.inf", older: [{ published: "oem8.inf", original: "nv_dispi.inf", provider: "NVIDIA", class: "Display", date: "05/14/2024", version: "31.0.15.5222" }] }],
    withoutDump: 0,
    verifier: [],
  },
  vulnerable_programs: { checked: 120, dbDate: "septiembre de 2025", hits: [{ name: "7-Zip 19.00 (x64)", version: "19.00", fixed: "24.09", cve: "CVE-2025-0411", exploited: true, what: "Un archivo comprimido puede saltarse el aviso.", winget: "7zip.7zip", eol: false }, { name: "Microsoft Office 2013", version: "15.0", fixed: "", cve: "", exploited: false, what: "Ya no tiene soporte.", winget: "", eol: true }] },
  rescue_status: { adk: false, winpe: false, kitsRoot: "", usb: [{ number: 2, name: "Kingston DataTraveler", size: 16_000_000_000, letters: ["E"], system: false }] },
  perf_insights: { samples: 600, hours: 10, leaks: [{ name: "Teams.exe", fromMb: 400, toMb: 3100, hours: 6, at: 1_728_000_000, series: [] }], saturatedMinutes: 12, diskHogs: [{ name: "SearchIndexer.exe", minutes: 10, avgKbs: 30000 }], peak: { hour: 17, cpu: 80, busy: 60, names: ["backup.exe"] } },
  event_digest: [{ provider: "disk", id: 7, log: "System", count: 3, last: 1_728_000_000, weight: "matter", title: "Sectores dañados en un disco", meaning: "El disco no pudo leer un bloque.", todo: "Copia de seguridad ya.", page: "space", sample: "El dispositivo tiene un bloque defectuoso." }],
  security_audit: { score: 82, checks: [{ id: "fw", label: "Cortafuegos", status: "ok", detail: "Activo en los tres perfiles", weight: 10, fix: null }], vulnerable: [] },
};
