// Respuestas de ejemplo para las órdenes que, vacías, no dejarían pintar una
// pantalla (las que devuelven un objeto). Las listas vacías, cadenas y números
// los pone el simulador solo.
export const FIXTURES: Record<string, unknown> = {
  app_info: { version: "1.2.8", portable: true, dataDir: "D:\\AdminOps\\datos", reportsDir: "D:\\AdminOps\\informes", startPage: null },
  is_admin: true,
  lock_status: { enabled: false, kind: "", idleMinutes: 0, waitSecs: 0 },
  get_settings: {
    technician: "Técnico de prueba",
    company: "Soporte de ejemplo",
    phone: "",
    email: "",
    website: "",
    logo: null,
    conditions: "",
    checklist: [],
    onboarded: true,
    defaultDomain: "",
    notifyTasks: true,
    restorePoints: "risky",
    autoCleanupMonths: 0,
    checkUpdates: false,
    watchWindows: false,
    notifyAlerts: "all",
    closeMinimizes: false,
    trayIcon: false,
    visitTypes: [],
    currency: "EUR",
    taxName: "IVA",
    taxRate: 21,
    laborWarrantyDays: 90,
    maintenanceMonths: 6,
    quoteValidityDays: 30,
    catalog: [],
    techSignature: null,
    reportLayout: { name: "", technical: false, sections: [] },
  },
  get_system_info: { hostName: "PC-PRUEBAS", osName: "Windows 11 Pro", osVersion: "23H2", kernelVersion: "22631", cpuBrand: "Intel Core i5-10500", physicalCores: 6, logicalCores: 12, totalMemory: 16 * 2 ** 30, bootTime: Math.floor(Date.now() / 1000) - 3 * 3600 },
  get_live_metrics: () => ({
    cpuTotal: 10 + Math.random() * 30,
    cpuPerCore: Array.from({ length: 12 }, () => Math.random() * 60),
    memoryUsed: 7.4 * 2 ** 30,
    memoryTotal: 16 * 2 ** 30,
    swapUsed: 0,
    swapTotal: 2 ** 31,
    uptime: 3 * 3600,
    processCount: 214,
    netRxPerSec: 120_000,
    netTxPerSec: 30_000,
    disks: [{ mount: "C:\\", name: "Windows", fileSystem: "NTFS", kind: "SSD", total: 512 * 2 ** 30, available: 180 * 2 ** 30, removable: false }],
    topProcesses: [],
  }),
  recover_status: { installed: false, drives: [] },
  dns_filter_status: { active: "none", adapters: ["Ethernet"] },
  update_pause_state: { pausedUntil: null },
  network_drives: { drives: [], free: ["Z:", "Y:", "X:"] },
  security_audit: { score: 82, checks: [{ id: "fw", label: "Cortafuegos", status: "ok", detail: "Activo en los tres perfiles", weight: 10, fix: null }], vulnerable: [] },
};
